/**
 * Aegis Procure — Preprod Deployment Script
 *
 * Deploys the compiled aegis.compact contract to Midnight Preprod.
 *
 * Usage:
 *   npx tsx scripts/deploy.ts
 *
 * Prerequisites:
 *   1. Run `npm run compact:build` first — ZK circuits must be in /managed
 *   2. Set environment variables in .env.local (see below)
 *   3. Lace wallet funded with tDUST on Preprod
 *      Faucet: https://faucet.midnight.network
 *
 * Required env vars (.env.local):
 *   NEXT_PUBLIC_MIDNIGHT_INDEXER_URL   — e.g. https://indexer.preprod.midnight.network/api/v1/graphql
 *   NEXT_PUBLIC_MIDNIGHT_PROOF_SERVER_URL — e.g. https://proof.preprod.midnight.network
 *   DEPLOY_WALLET_SEED                 — your wallet seed phrase (never commit this)
 */

import { deployContract, findDeployedContract } from "@midnight-ntwrk/midnight-js-contracts";
import { setNetworkId } from "@midnight-ntwrk/midnight-js-network-id";
import { FetchZkConfigProvider } from "@midnight-ntwrk/midnight-js-fetch-zk-config-provider";
import { httpClientProofProvider } from "@midnight-ntwrk/midnight-js-http-client-proof-provider";
import { indexerPublicDataProvider } from "@midnight-ntwrk/midnight-js-indexer-public-data-provider";
import { levelPrivateStateProvider } from "@midnight-ntwrk/midnight-js-level-private-state-provider";
import type { MidnightProviders } from "@midnight-ntwrk/midnight-js-types";

// ---------------------------------------------------------------------------
// Load environment
// ---------------------------------------------------------------------------
const INDEXER_URL =
  process.env.NEXT_PUBLIC_MIDNIGHT_INDEXER_URL ??
  "https://indexer.preprod.midnight.network/api/v1/graphql";

const PROOF_SERVER_URL =
  process.env.NEXT_PUBLIC_MIDNIGHT_PROOF_SERVER_URL ??
  "https://proof.preprod.midnight.network";

const NETWORK: "testnet" | "mainnet" = "testnet"; // Preprod = testnet

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main() {
  console.log("🔒 Aegis Procure — Preprod Deployment");
  console.log("======================================");
  console.log(`Network:      ${NETWORK} (Preprod)`);
  console.log(`Indexer:      ${INDEXER_URL}`);
  console.log(`Proof server: ${PROOF_SERVER_URL}`);
  console.log("");

  // 1. Set network ID
  setNetworkId(NETWORK);
  console.log("✓ Network ID set to testnet (Preprod)");

  // 2. Import compiled contract artifacts from /managed
  //    (generated by `npm run compact:build`)
  let contract: unknown;
  try {
    // The Compact compiler outputs a JS module at managed/contract/index.cjs
    // Adjust the path if your compact output differs
    contract = await import("../managed/contract/index.cjs");
    console.log("✓ Compiled contract artifacts loaded from /managed");
  } catch (err) {
    console.error(
      "✗ Could not load compiled contract. Run `npm run compact:build` first."
    );
    console.error(err);
    process.exit(1);
  }

  // 3. Build providers
  const zkConfigProvider = new FetchZkConfigProvider(
    `${PROOF_SERVER_URL}/zk-config`
  );

  const proofProvider = httpClientProofProvider(
    PROOF_SERVER_URL,
    zkConfigProvider
  );

  const publicDataProvider = indexerPublicDataProvider(
    INDEXER_URL,
    INDEXER_URL.replace("https://", "wss://").replace("http://", "ws://")
  );

  const privateStateProvider = levelPrivateStateProvider({
    privateStoragePasswordProvider: () =>
      process.env.PRIVATE_STATE_PASSWORD ?? "aegis-procure-dev",
    accountId: "aegis-procure-deployer",
  });

  // NOTE: In a real deployment you would wire in a wallet provider here.
  // For CLI deployment, use @midnight-ntwrk/midnight-js-wallet or
  // the Lace DApp Connector if deploying from a browser context.
  // See: https://github.com/midnightntwrk/example-counter
  const providers = {
    privateStateProvider,
    publicDataProvider,
    zkConfigProvider,
    proofProvider,
    // walletProvider and midnightProvider must be supplied for a real deployment
    // walletProvider: ...,
    // midnightProvider: ...,
  } as unknown as MidnightProviders;

  console.log("✓ Providers configured");

  // 4. Deploy
  console.log("\nDeploying contract to Midnight Preprod...");
  console.log("(This may take 30–60 seconds while the ZK proof is generated)");

  try {
    const deployed = await deployContract(providers, {
      // @ts-expect-error — contract shape depends on Compact compiler output
      compiledContract: contract,
      privateStateId: "aegis-procure-private-state",
      initialPrivateState: {
        lowestBid: 0n,
        lowestBidder: "0".repeat(64),
      },
    });

    const contractAddress = deployed.deployTxData.public.contractAddress;

    console.log("\n✅ Contract deployed successfully!");
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.log(`Contract Address: ${contractAddress}`);
    console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    console.log("\nNext steps:");
    console.log(`  1. Update README.md → Contract Address table with: ${contractAddress}`);
    console.log(`  2. Update .env.local → NEXT_PUBLIC_CONTRACT_ADDRESS=${contractAddress}`);
    console.log(
      `  3. View on explorer: https://explorer.preprod.midnight.network/contract/${contractAddress}`
    );
  } catch (err) {
    console.error("\n✗ Deployment failed:");
    console.error(err);
    console.error("\nCommon causes:");
    console.error("  - Wallet not funded with tDUST (faucet: https://faucet.midnight.network)");
    console.error("  - Proof server unreachable");
    console.error("  - walletProvider / midnightProvider not wired in (see script comments)");
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
